name: Deploy Production Website

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "static/sbom/**"
      - "content/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/deploy-prod.yml"
      - "svelte.config.js"
      - "wrangler.jsonc"

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: depot-ubuntu-latest
    environment:
      name: production
      url: https://getarcane.app

    steps:
      - name: Checkout arcane website repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout arcane repo
        uses: actions/checkout@v6
        with:
          repository: getarcaneapp/arcane
          path: arcane
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v6

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate swagger.yaml
        run: |
          swag init -d ./arcane/backend/cmd,./arcane/backend/internal,./arcane/backend/internal/dto -g ./main.go -ot yaml -o ./static/apiref -md ./content --parseInternal

      - name: Remove arcane repo folder
        run: rm -rf arcane

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm exec wrangler deploy
